"""The 0013 rollback marker is not application-schema drift."""

from __future__ import annotations

import importlib.util
import io
import json
from contextlib import nullcontext
from pathlib import Path
from unittest.mock import Mock, patch

import pytest
from alembic import command, context
from alembic.config import Config
from alembic.operations import ops
from alembic.script import ScriptDirectory
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, literal, text

from conftest import make_alembic_config

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
ENV_PY = REPOSITORY_ROOT / "database" / "migrations" / "env.py"
MARKER_QUERY = text(
    "select obj_description('public.app_users'::regclass, 'pg_class')"
)
VALID_MARKER = json.dumps(
    {
        "revision": "0013_default_acl_hardening",
        "owner": "app_owner",
        "defaults": {},
    }
)


@pytest.fixture(scope="module")
def env_module():
    """Import env.py without starting an Alembic migration environment."""
    config = Config()
    fake_context = {
        "config": config,
        "is_offline_mode": Mock(return_value=True),
        "configure": Mock(),
        "begin_transaction": Mock(return_value=nullcontext()),
        "run_migrations": Mock(),
    }
    with (
        patch.dict(context.__dict__, fake_context),
        patch.dict(
            "os.environ", {"EMBYR_DATABASE_URL": "postgresql://unused/test"}
        ),
    ):
        spec = importlib.util.spec_from_file_location("a8_env_under_test", ENV_PY)
        assert spec is not None and spec.loader is not None
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def marker_recognizer(env_module):
    return env_module._is_0013_default_acl_marker


@pytest.mark.parametrize(
    "comment",
    [
        None,
        "not json",
        "{}",
        "[]",
        json.dumps({"revision": "wrong", "owner": "app_owner", "defaults": {}}),
        json.dumps(
            {"revision": "0013_default_acl_hardening", "owner": "wrong", "defaults": {}}
        ),
        json.dumps(
            {"revision": "0013_default_acl_hardening", "owner": "app_owner"}
        ),
        json.dumps(
            {
                "revision": "0013_default_acl_hardening",
                "owner": "app_owner",
                "defaults": [],
            }
        ),
        json.dumps(
            {
                "revision": "0013_default_acl_hardening",
                "owner": "app_owner",
                "defaults": {},
                "extra": True,
            }
        ),
    ],
)
def test_marker_recognizer_rejects_lookalikes(marker_recognizer, comment):
    assert marker_recognizer(comment) is False


def test_marker_recognizer_accepts_exact_structure(marker_recognizer):
    assert marker_recognizer(
        json.dumps(
            {
                "revision": "0013_default_acl_hardening",
                "owner": "app_owner",
                "defaults": {"environment_specific": ["state"]},
            }
        )
    )


@pytest.mark.parametrize(
    ("table_name", "schema", "suppressed"),
    [
        ("app_users", None, True),
        ("app_users", "public", True),
        ("app_users", "private", False),
        ("other_table", "public", False),
    ],
)
def test_rewrite_is_scoped_to_public_app_users(
    env_module, table_name: str, schema: str | None, suppressed: bool
):
    operation = ops.DropTableCommentOp(
        table_name, schema=schema, existing_comment=VALID_MARKER
    )
    result = env_module._preserve_0013_default_acl_marker(None, None, operation)
    if suppressed:
        assert result == []
    else:
        assert result is operation


def test_arbitrary_drop_comment_operation_is_preserved(env_module):
    operation = ops.DropTableCommentOp(
        "app_users", existing_comment="ordinary application comment"
    )
    assert (
        env_module._preserve_0013_default_acl_marker(None, None, operation)
        is operation
    )


@pytest.mark.parametrize(
    ("table_name", "schema", "comment", "suppressed"),
    [
        ("app_users", None, VALID_MARKER, True),
        ("app_users", "public", VALID_MARKER, True),
        ("app_users", "private", VALID_MARKER, False),
        ("other_table", "public", VALID_MARKER, False),
        ("app_users", None, "ordinary application comment", False),
        ("app_users", None, "not json", False),
    ],
)
def test_create_comment_rewrite_is_marker_specific(
    env_module,
    table_name: str,
    schema: str | None,
    comment: str,
    suppressed: bool,
):
    operation = ops.CreateTableCommentOp(
        table_name, comment, schema=schema
    )
    result = env_module._omit_0013_default_acl_marker_from_downgrade(
        None, None, operation
    )
    if suppressed:
        assert result == []
    else:
        assert result is operation


@pytest.mark.parametrize(
    ("comment", "suppressed"),
    [
        (VALID_MARKER, True),
        ("ordinary application comment", False),
    ],
)
def test_rewriter_filters_both_sides_of_migration_script(
    env_module, comment: str, suppressed: bool
):
    drop = ops.DropTableCommentOp("app_users", existing_comment=comment)
    create = drop.reverse()
    script = ops.MigrationScript(
        None,
        ops.UpgradeOps(ops=[drop]),
        ops.DowngradeOps(ops=[create]),
    )
    directives = [script]

    env_module.autogenerate_rewriter(None, None, directives)

    assert directives == [script]
    if suppressed:
        assert script.upgrade_ops.ops == []
        assert script.downgrade_ops.ops == []
    else:
        assert script.upgrade_ops.ops == [drop]
        assert script.downgrade_ops.ops == [create]


def _table_comment(engine: Engine) -> str | None:
    with engine.connect() as connection:
        return connection.execute(MARKER_QUERY).scalar_one()


def _set_table_comment(engine: Engine, comment: str) -> None:
    quoted = literal(comment).compile(
        dialect=engine.dialect, compile_kwargs={"literal_binds": True}
    )
    with engine.begin() as connection:
        connection.exec_driver_sql(f"comment on table public.app_users is {quoted}")


def test_real_marker_is_preserved_by_alembic_check(
    database_url: str, migrated_engine: Engine
):
    marker_before = _table_comment(migrated_engine)
    assert marker_before is not None
    assert json.loads(marker_before).keys() == {"revision", "owner", "defaults"}
    assert json.loads(marker_before)["revision"] == "0013_default_acl_hardening"
    assert json.loads(marker_before)["owner"] == "app_owner"

    config = make_alembic_config(database_url)
    config.stdout = io.StringIO()
    command.check(config)

    assert "No new upgrade operations detected." in config.stdout.getvalue()
    assert _table_comment(migrated_engine) == marker_before


def test_arbitrary_app_users_comment_is_detected(
    database_url: str, migrated_engine: Engine
):
    original = _table_comment(migrated_engine)
    assert original is not None
    try:
        _set_table_comment(migrated_engine, "ordinary application comment")
        with pytest.raises(AutogenerateDiffsDetected) as error:
            command.check(make_alembic_config(database_url))
        assert any(diff[0] == "remove_table_comment" for diff in error.value.diffs)
    finally:
        _set_table_comment(migrated_engine, original)
    assert _table_comment(migrated_engine) == original


def test_unrelated_schema_drift_is_detected(
    database_url: str, migrated_engine: Engine
):
    with migrated_engine.begin() as connection:
        connection.execute(text("create table public.a8_unrelated_drift (id integer)"))
    try:
        with pytest.raises(AutogenerateDiffsDetected) as error:
            command.check(make_alembic_config(database_url))
        assert any(
            diff[0] == "remove_table" and diff[1].name == "a8_unrelated_drift"
            for diff in error.value.diffs
        )
    finally:
        with migrated_engine.begin() as connection:
            connection.execute(text("drop table public.a8_unrelated_drift"))


def test_single_expected_alembic_head(database_url: str):
    assert [
        head.revision
        for head in ScriptDirectory.from_config(make_alembic_config(database_url))
        .get_revisions("heads")
    ] == ["0019_response_lock_security"]
